@startuml
left to right direction
skinparam packageStyle rectangle
skinparam componentStyle uml2

component "protocolo" {
  package "JsonSerializer" {
    class ResponseBuilder
  }
  package "MessageParser" {
    class BroadcastManager
    interface FederatedBroadcastHook
    class JsonInputParser
    class MessageWrapper
  }
  package "RequestRouter" {
    class MainRouter
    class TransferManager
    class TransferTicket
    interface ActionHandler
  }
  package "RequestRouter.handlers" {
    class SendMessageHandler
    class ListLogsHandler
    class ListPeerLogsHandler
    class ListDocumentsHandler
    class DownloadInitHandler
    class UploadInitHandler
    class ListMessagesHandler
    class ListClientsHandler
    class ConnectHandler
    class ListPeerInfoHandler
  }
}
component "red" {
  package "protocolSelector" {
    class ProtocolSelector
  }
  package "tcpsocketserver" {
    class TCPSocketServer
  }
  package "udpsocketserver" {
    class UDPSocketServer
  }
}
component "persistencia" {
  package "MySqlRepository" {
    class MySqlDao
    class MySqlRepositoryFactory
    class SqlScriptRunner
    class DatabaseInitializer
    class DatabaseConnectionManager
  }
  package "FileSystemStorage" {
    class LocalFileManager
  }
}
component "servicios" {
  package "ports.spi" {
    interface IDocumentRepository
    interface RepositoryFactory
    interface IUserRepository
    interface ISessionRepository
    interface IAuditLogRepository
  }
  package "DocumentService" {
    class CryptoResult
    class DocumentManager
  }
  package "LogService" {
    class LogManager
  }
  package "FileStorageService" {
    class StorageManager
  }
  package "UserService" {
    class UserManager
  }
  package "CryptoService" {
    class CryptoManager
  }
}
component "gestion-de-conexiones" {
  package "pool" {
    class PooledClientConnection
    class ConnectionPoolManager
    interface IConnectionPool
  }
  package "executor" {
    class ThreadPoolManager
  }
  package "handler" {
    class LineReader
    class FileTransferHandler
    class ClientHandler
  }
}
component "main" {
  class ServerApplication
  package "api" {
    class ServerAdminAPI
  }
  package "console" {
    class InteractiveConsole
  }
  package "config" {
    class ServerConfig
    class NodeSetupWizard
  }
}
component "cluster" {
  package "health" {
    class ClusterHealthService
    class NodeHealthReport
    class ClusterHealthReport
  }
  package "topology" {
    class RoutingTable
  }
  package "events" {
    class NodeInfo
    class NetworkEventBus
    interface NetworkEventListener
    enum ClusterEvent
    class ClusterNotifier
  }
  package "communication" {
    class PeerServer
    class PeerConnectionPool
    class PeerMessageHandler
    class PeerConnection
    class InterServerProtocol
  }
  package "identity" {
    class NodeIdentity
  }
  package "registry" {
    class LocalClientRegistry
  }
  package "routing" {
    class LocalDeliveryStrategy
    class RemoteDeliveryStrategy
    class FederatedBroadcastStrategy
    interface MessageRoutingStrategy
  }
  package "replication" {
    class EventDeduplicator
    class ReplicationManager
    class ReplicationEvent
  }
  package "discovery" {
    class MemberEntry
    class GossipProtocol
    class MembershipList
    enum NodeState
  }
}

BroadcastManager --> FederatedBroadcastHook
MainRouter --> ResponseBuilder
MainRouter --> JsonInputParser
MainRouter --> ListLogsHandler
MainRouter --> MessageWrapper
MainRouter --> UserManager
MainRouter --> ListMessagesHandler
MainRouter --> ReplicationManager
MainRouter --> ListClientsHandler
MainRouter --> SendMessageHandler
MainRouter --> LocalClientRegistry
MainRouter --> ConnectHandler
MainRouter --> ActionHandler
MainRouter --> BroadcastManager
MainRouter --> RoutingTable
MainRouter --> ListDocumentsHandler
MainRouter --> LogManager
ActionHandler <|.. SendMessageHandler
SendMessageHandler --> BroadcastManager
SendMessageHandler --> ResponseBuilder
SendMessageHandler --> LocalClientRegistry
SendMessageHandler --> ListLogsHandler
SendMessageHandler --> RemoteDeliveryStrategy
SendMessageHandler --> UserManager
SendMessageHandler --> RoutingTable
SendMessageHandler --> DocumentManager
SendMessageHandler --> LogManager
SendMessageHandler --> ReplicationManager
ActionHandler <|.. ListLogsHandler
ListLogsHandler --> ResponseBuilder
ListLogsHandler --> LogManager
ActionHandler <|.. ListPeerLogsHandler
ListPeerLogsHandler --> MembershipList
ListPeerLogsHandler --> ResponseBuilder
ActionHandler <|.. ListDocumentsHandler
ListDocumentsHandler --> ResponseBuilder
ListDocumentsHandler --> DocumentManager
ActionHandler <|.. DownloadInitHandler
DownloadInitHandler --> BroadcastManager
DownloadInitHandler --> ResponseBuilder
DownloadInitHandler --> ListLogsHandler
DownloadInitHandler --> TransferTicket
DownloadInitHandler --> UserManager
DownloadInitHandler --> DocumentManager
DownloadInitHandler --> LogManager
DownloadInitHandler --> TransferManager
ActionHandler <|.. UploadInitHandler
UploadInitHandler --> BroadcastManager
UploadInitHandler --> ResponseBuilder
UploadInitHandler --> ListLogsHandler
UploadInitHandler --> TransferTicket
UploadInitHandler --> UserManager
UploadInitHandler --> LogManager
UploadInitHandler --> TransferManager
ActionHandler <|.. ListMessagesHandler
ListMessagesHandler --> DocumentManager
ListMessagesHandler --> ResponseBuilder
ActionHandler <|.. ListClientsHandler
ListClientsHandler --> ResponseBuilder
ListClientsHandler --> UserManager
ListClientsHandler --> RoutingTable
ActionHandler <|.. ConnectHandler
ConnectHandler --> BroadcastManager
ConnectHandler --> ListClientsHandler
ConnectHandler --> ResponseBuilder
ConnectHandler --> LocalClientRegistry
ConnectHandler --> ReplicationEvent
ConnectHandler --> UserManager
ConnectHandler --> RoutingTable
ConnectHandler --> LogManager
ConnectHandler --> ReplicationManager
ActionHandler <|.. ListPeerInfoHandler
ListPeerInfoHandler --> MembershipList
ListPeerInfoHandler --> ResponseBuilder
ListPeerInfoHandler --> NodeIdentity
ListPeerInfoHandler --> ClusterHealthService
ProtocolSelector --> TCPSocketServer
ProtocolSelector --> UDPSocketServer
TCPSocketServer --> BroadcastManager
TCPSocketServer --> PooledClientConnection
TCPSocketServer --> ThreadPoolManager
TCPSocketServer --> IConnectionPool
TCPSocketServer --> MainRouter
TCPSocketServer --> DocumentManager
TCPSocketServer --> TransferManager
UDPSocketServer --> ThreadPoolManager
UDPSocketServer --> MainRouter
IUserRepository <|.. MySqlDao
IDocumentRepository <|.. MySqlDao
ISessionRepository <|.. MySqlDao
IAuditLogRepository <|.. MySqlDao
MySqlDao --> DatabaseConnectionManager
RepositoryFactory <|.. MySqlRepositoryFactory
MySqlRepositoryFactory --> MySqlDao
DocumentManager --> CryptoResult
DocumentManager --> IUserRepository
DocumentManager --> CryptoManager
DocumentManager --> IDocumentRepository
DocumentManager --> LogManager
DocumentManager --> LocalFileManager
LogManager --> IAuditLogRepository
UserManager --> IUserRepository
UserManager --> ISessionRepository
IConnectionPool <|.. ConnectionPoolManager
ConnectionPoolManager --> PooledClientConnection
FileTransferHandler --> BroadcastManager
FileTransferHandler --> TransferTicket
FileTransferHandler --> MainRouter
FileTransferHandler --> DocumentManager
FileTransferHandler --> TransferManager
ClientHandler --> BroadcastManager
ClientHandler --> IConnectionPool
ClientHandler --> MainRouter
ClientHandler --> PooledClientConnection
ServerApplication --> MembershipList
ServerApplication --> ThreadPoolManager
ServerApplication --> UserManager
ServerApplication --> PeerConnectionPool
ServerApplication --> ClusterHealthService
ServerApplication --> RepositoryFactory
ServerApplication --> LocalClientRegistry
ServerApplication --> ServerConfig
ServerApplication --> ClusterNotifier
ServerApplication --> ServerAdminAPI
ServerApplication --> PeerServer
ServerApplication --> NetworkEventBus
ServerApplication --> ISessionRepository
ServerApplication --> ProtocolSelector
ServerApplication --> CryptoManager
ServerApplication --> IAuditLogRepository
ServerApplication --> MainRouter
ServerApplication --> BroadcastManager
ServerApplication --> IUserRepository
ServerApplication --> IDocumentRepository
ServerApplication --> ConnectionPoolManager
ServerApplication --> RoutingTable
ServerApplication --> LogManager
ServerApplication --> LocalFileManager
ServerApplication --> TransferManager
ServerAdminAPI --> IDocumentRepository
ServerAdminAPI --> IUserRepository
InteractiveConsole --> MembershipList
InteractiveConsole --> ProtocolSelector
InteractiveConsole --> ServerAdminAPI
InteractiveConsole --> RoutingTable
InteractiveConsole --> ClusterHealthService
ClusterHealthService --> MembershipList
ClusterHealthService --> NodeIdentity
ClusterHealthService --> NodeState
ClusterHealthService --> ClusterHealthReport
ClusterHealthService --> PeerConnectionPool
NodeHealthReport --> NodeState
NetworkEventListener <|.. RoutingTable
NetworkEventListener <|.. ClusterNotifier
PeerServer --> PeerMessageHandler
NetworkEventListener <|.. PeerConnectionPool
PeerConnectionPool --> PeerConnection
PeerMessageHandler --> ReplicationEvent
PeerMessageHandler --> LocalClientRegistry
PeerMessageHandler --> RoutingTable
PeerMessageHandler --> ReplicationManager
MessageRoutingStrategy <|.. LocalDeliveryStrategy
MessageRoutingStrategy <|.. RemoteDeliveryStrategy
RemoteDeliveryStrategy --> PeerConnectionPool
RemoteDeliveryStrategy --> RoutingTable
MessageRoutingStrategy <|.. FederatedBroadcastStrategy
FederatedBroadcastStrategy --> PeerConnectionPool
NetworkEventListener <|.. ReplicationManager
ReplicationManager --> MembershipList
ReplicationManager --> PeerConnectionPool
ReplicationManager --> EventDeduplicator
MemberEntry --> NodeInfo
MemberEntry --> NodeState
GossipProtocol --> MembershipList
GossipProtocol --> NetworkEventBus
GossipProtocol --> NodeIdentity
GossipProtocol --> NodeState
GossipProtocol --> NodeInfo
MembershipList --> MemberEntry
MembershipList --> NodeState
@enduml