@startuml
left to right direction
skinparam packageStyle rectangle
skinparam componentStyle uml2

component "protocolo" {
  class ProtocolTester
  package "JsonSerializer" {
    class ResponseBuilder
  }
  package "MessageParser" {
    class BroadcastManager
    interface FederatedBroadcastHook
    class JsonInputParser
    class MessageWrapper
  }
  package "RequestRouter" {
    class MainRouter
    class TransferManager
    class TransferTicket
    interface ActionHandler
  }
  package "RequestRouter.handlers" {
    class SendMessageHandler
    class DownloadInitHandler
    class UploadInitHandler
    class ConnectHandler
  }
}
component "cliente-mensajeria" {
  package "network.handlers" {
    class ListLogsHandler
    class ListPeerLogsHandler
    class ListDocumentsHandler
    class ListMessagesHandler
    class ListClientsHandler
    class ListPeerInfoHandler
    class DownloadInitAckHandler
    class SendMessageAckHandler
    class UploadStatusHandler
    class NewMessageHandler
    class ConnectAckHandler
    interface MessageHandler
    class ServerJoinedHandler
    class UploadInitAckHandler
    class ServerLeftHandler
  }
  package "config" {
    class AppConfig
  }
  class Main
  package "ui" {
    class SwingEventPublisher
    class VentanaConexion
    class Dashboard
  }
  package "ui.componentes" {
    class ComponenteTablaMensajes
    class ComponenteClientes
    class ComponenteServidores
    class MensajeCopiableEditor
    class ComponenteLogs
    class EditorGenerico
    class ComponenteTablaArchivos
    class MensajeCopiableRenderer
    class RendererGenerico
    class ComponentePeerLogs
    class PanelBotonesGenerico
  }
  package "data" {
    class H2ChatRepository
    class H2Database
  }
  package "domain.ports" {
    interface UIEventPublisher
    interface ChatRepository
  }
  package "models" {
    class MessageRequest
  }
  package "network" {
    class UDPClient
    class JSONSerializer
    class ConnectionHandler
    class TCPClient
    class ClientRouter
  }
}
component "red" {
  package "protocolSelector" {
    class ProtocolSelector
  }
  package "tcpsocketserver" {
    class TCPSocketServer
  }
  package "udpsocketserver" {
    class UDPSocketServer
  }
}
component "persistencia" {
  class PersistenceTester
  package "MySqlRepository" {
    interface IDocumentRepository
    class MySqlDao
    class SqlScriptRunner
    class DatabaseInitializer
    interface IUserRepository
    interface ISessionRepository
    interface IAuditLogRepository
  }
  package "FileSystemStorage" {
    class LocalFileManager
  }
}
component "P2P_Server" {
  package "com.universidad.messaging.server.repository.pool" {
    class DatabaseConnectionManager
  }
  package "com.universidad.messaging.server" {
    class ServerMain
    class App
    class AppTest
  }
  package "com.universidad.messaging.server.pool" {
    class ClientConnectionPool
    interface Poolable
  }
  package "com.universidad.messaging.server.storage" {
    class StorageService
  }
  package "com.universidad.messaging.server.business" {
    interface MessageProcessor
    class DefaultMessageProcessor
  }
  package "com.universidad.messaging.server.network" {
    class UDPServer
    class TCPServer
  }
}
component "servicios" {
  class ServiceTester
  package "DocumentService" {
    class CryptoResult
    class DocumentManager
  }
  package "LogService" {
    class LogManager
  }
  package "FileStorageService" {
    class StorageManager
  }
  package "UserService" {
    class UserManager
  }
  package "CryptoService" {
    class CryptoManager
  }
}
component "shared" {
  package "EncryptionUtils" {
    class EncryptionUtils
    interface IEncryptionUtils
  }
  package "JsonSchema" {
    class UserRecord
    class FederatedClientInfo
    class DownloadDetails
    enum DownloadMode
    class LogEntry
    class ActiveClient
    class JsonSchema
    class ClientAddress
    enum DocType
    class DocumentInfo
  }
}
component "gestion-de-conexiones" {
  package "pool" {
    class PooledClientConnection
    class ConnectionPoolManager
    interface IConnectionPool
  }
  package "handler" {
    class ClientHandler
    class LineReader
    class FileTransferHandler
  }
  package "executor" {
    class ThreadPoolManager
  }
}
component "main" {
  class ServerApplication
  package "api" {
    class ServerAdminAPI
  }
  package "console" {
    class InteractiveConsole
  }
  package "config" {
    class ServerConfig
    class NodeSetupWizard
  }
}
component "cluster" {
  package "health" {
    class ClusterHealthService
    class NodeHealthReport
    class ClusterHealthReport
  }
  package "topology" {
    class RoutingTable
  }
  package "events" {
    class NodeInfo
    class NetworkEventBus
    interface NetworkEventListener
    enum ClusterEvent
    class ClusterNotifier
  }
  package "communication" {
    class PeerServer
    class PeerConnectionPool
    class PeerMessageHandler
    class PeerConnection
    class InterServerProtocol
  }
  package "identity" {
    class NodeIdentity
  }
  package "registry" {
    class LocalClientRegistry
  }
  package "routing" {
    class LocalDeliveryStrategy
    class RemoteDeliveryStrategy
    class FederatedBroadcastStrategy
    interface MessageRoutingStrategy
  }
  package "replication" {
    class EventDeduplicator
    class ReplicationManager
    class ReplicationEvent
  }
  package "discovery" {
    class MemberEntry
    class GossipProtocol
    class MembershipList
    enum NodeState
  }
}

BroadcastManager --> FederatedBroadcastHook
MainRouter --> ClientAddress
MainRouter --> ListDocumentsHandler
MainRouter --> MessageWrapper
MainRouter --> ListLogsHandler
MainRouter --> ListMessagesHandler
MainRouter --> BroadcastManager
MainRouter --> ResponseBuilder
MainRouter --> ConnectHandler
MainRouter --> ListClientsHandler
MainRouter --> SendMessageHandler
MainRouter --> RoutingTable
MainRouter --> JsonInputParser
MainRouter --> UserManager
MainRouter --> LocalClientRegistry
MainRouter --> LogManager
MainRouter --> ActionHandler
MainRouter --> ReplicationManager
ActionHandler <|.. SendMessageHandler
SendMessageHandler --> UserManager
SendMessageHandler --> RoutingTable
SendMessageHandler --> BroadcastManager
SendMessageHandler --> ResponseBuilder
SendMessageHandler --> DocumentManager
SendMessageHandler --> RemoteDeliveryStrategy
SendMessageHandler --> LocalClientRegistry
SendMessageHandler --> LogManager
SendMessageHandler --> ReplicationManager
SendMessageHandler --> ListLogsHandler
MessageHandler <|.. ListLogsHandler
ListLogsHandler --> UIEventPublisher
MessageHandler <|.. ListPeerLogsHandler
ListPeerLogsHandler --> UIEventPublisher
MessageHandler <|.. ListDocumentsHandler
ListDocumentsHandler --> UIEventPublisher
ActionHandler <|.. DownloadInitHandler
DownloadInitHandler --> UserManager
DownloadInitHandler --> DownloadDetails
DownloadInitHandler --> BroadcastManager
DownloadInitHandler --> ResponseBuilder
DownloadInitHandler --> DocumentManager
DownloadInitHandler --> TransferManager
DownloadInitHandler --> TransferTicket
DownloadInitHandler --> LogManager
DownloadInitHandler --> ListLogsHandler
ActionHandler <|.. UploadInitHandler
UploadInitHandler --> UserManager
UploadInitHandler --> BroadcastManager
UploadInitHandler --> ResponseBuilder
UploadInitHandler --> TransferManager
UploadInitHandler --> TransferTicket
UploadInitHandler --> LogManager
UploadInitHandler --> ListLogsHandler
MessageHandler <|.. ListMessagesHandler
ListMessagesHandler --> UIEventPublisher
MessageHandler <|.. ListClientsHandler
ListClientsHandler --> UIEventPublisher
ActionHandler <|.. ConnectHandler
ConnectHandler --> UserManager
ConnectHandler --> RoutingTable
ConnectHandler --> BroadcastManager
ConnectHandler --> ResponseBuilder
ConnectHandler --> ClientAddress
ConnectHandler --> LocalClientRegistry
ConnectHandler --> ReplicationEvent
ConnectHandler --> ListClientsHandler
ConnectHandler --> LogManager
ConnectHandler --> ReplicationManager
MessageHandler <|.. ListPeerInfoHandler
ListPeerInfoHandler --> UIEventPublisher
ProtocolSelector --> TCPSocketServer
ProtocolSelector --> UDPSocketServer
TCPSocketServer --> BroadcastManager
TCPSocketServer --> ThreadPoolManager
TCPSocketServer --> IConnectionPool
TCPSocketServer --> DocumentManager
TCPSocketServer --> TransferManager
TCPSocketServer --> PooledClientConnection
TCPSocketServer --> MainRouter
UDPSocketServer --> ThreadPoolManager
UDPSocketServer --> MainRouter
IUserRepository <|.. MySqlDao
IDocumentRepository <|.. MySqlDao
ISessionRepository <|.. MySqlDao
IAuditLogRepository <|.. MySqlDao
MySqlDao --> DatabaseConnectionManager
DocumentManager --> DownloadDetails
DocumentManager --> CryptoResult
DocumentManager --> IDocumentRepository
DocumentManager --> CryptoManager
DocumentManager --> LocalFileManager
DocumentManager --> IUserRepository
DocumentManager --> LogManager
LogManager --> IAuditLogRepository
UserManager --> IUserRepository
UserManager --> ISessionRepository
CryptoManager --> IEncryptionUtils
IEncryptionUtils <|.. EncryptionUtils
ServerMain --> UDPServer
ServerMain --> ClientConnectionPool
ServerMain --> DatabaseConnectionManager
ServerMain --> MessageProcessor
ServerMain --> AppConfig
ServerMain --> TCPServer
ClientConnectionPool --> PooledClientConnection
MessageProcessor <|.. DefaultMessageProcessor
ClientHandler --> BroadcastManager
ClientHandler --> IConnectionPool
ClientHandler --> PooledClientConnection
ClientHandler --> MainRouter
UDPServer --> ClientConnectionPool
UDPServer --> MessageProcessor
TCPServer --> ClientHandler
TCPServer --> ClientConnectionPool
TCPServer --> MessageProcessor
TCPServer --> PooledClientConnection
IConnectionPool <|.. ConnectionPoolManager
ConnectionPoolManager --> PooledClientConnection
FileTransferHandler --> DownloadMode
FileTransferHandler --> BroadcastManager
FileTransferHandler --> DocumentManager
FileTransferHandler --> TransferManager
FileTransferHandler --> TransferTicket
FileTransferHandler --> MainRouter
ServerApplication --> MembershipList
ServerApplication --> CryptoManager
ServerApplication --> IEncryptionUtils
ServerApplication --> TransferManager
ServerApplication --> PeerServer
ServerApplication --> ServerConfig
ServerApplication --> PeerConnectionPool
ServerApplication --> BroadcastManager
ServerApplication --> MySqlDao
ServerApplication --> NetworkEventBus
ServerApplication --> ClusterHealthService
ServerApplication --> RoutingTable
ServerApplication --> LocalFileManager
ServerApplication --> ConnectionPoolManager
ServerApplication --> ServerAdminAPI
ServerApplication --> MainRouter
ServerApplication --> UserManager
ServerApplication --> ProtocolSelector
ServerApplication --> ThreadPoolManager
ServerApplication --> ClusterNotifier
ServerApplication --> LocalClientRegistry
ServerApplication --> LogManager
ServerAdminAPI --> IUserRepository
ServerAdminAPI --> IDocumentRepository
InteractiveConsole --> MembershipList
InteractiveConsole --> RoutingTable
InteractiveConsole --> ProtocolSelector
InteractiveConsole --> ServerAdminAPI
InteractiveConsole --> ClusterHealthService
ClusterHealthService --> MembershipList
ClusterHealthService --> NodeState
ClusterHealthService --> PeerConnectionPool
ClusterHealthService --> NodeIdentity
ClusterHealthService --> ClusterHealthReport
NodeHealthReport --> NodeState
NetworkEventListener <|.. RoutingTable
NetworkEventListener <|.. ClusterNotifier
PeerServer --> PeerMessageHandler
NetworkEventListener <|.. PeerConnectionPool
PeerConnectionPool --> PeerConnection
PeerMessageHandler --> RoutingTable
PeerMessageHandler --> LocalClientRegistry
PeerMessageHandler --> ReplicationEvent
PeerMessageHandler --> ReplicationManager
MessageRoutingStrategy <|.. LocalDeliveryStrategy
MessageRoutingStrategy <|.. RemoteDeliveryStrategy
RemoteDeliveryStrategy --> RoutingTable
RemoteDeliveryStrategy --> PeerConnectionPool
MessageRoutingStrategy <|.. FederatedBroadcastStrategy
FederatedBroadcastStrategy --> PeerConnectionPool
NetworkEventListener <|.. ReplicationManager
ReplicationManager --> MembershipList
ReplicationManager --> EventDeduplicator
ReplicationManager --> PeerConnectionPool
MemberEntry --> NodeInfo
MemberEntry --> NodeState
GossipProtocol --> MembershipList
GossipProtocol --> NodeState
GossipProtocol --> NodeIdentity
GossipProtocol --> NodeInfo
GossipProtocol --> NetworkEventBus
MembershipList --> NodeState
MembershipList --> MemberEntry
Main --> ChatRepository
Main --> AppConfig
Main --> VentanaConexion
Main --> H2Database
UIEventPublisher <|.. SwingEventPublisher
SwingEventPublisher --> Dashboard
VentanaConexion --> TCPClient
VentanaConexion --> ClientRouter
VentanaConexion --> SwingEventPublisher
VentanaConexion --> UDPClient
VentanaConexion --> ChatRepository
VentanaConexion --> Dashboard
Dashboard --> ChatRepository
Dashboard --> ComponentePeerLogs
Dashboard --> TCPClient
Dashboard --> UDPClient
Dashboard --> ComponenteTablaMensajes
Dashboard --> ComponenteServidores
Dashboard --> ComponenteLogs
Dashboard --> ComponenteTablaArchivos
Dashboard --> ComponenteClientes
EditorGenerico --> PanelBotonesGenerico
RendererGenerico --> PanelBotonesGenerico
ChatRepository <|.. H2ChatRepository
H2ChatRepository --> H2Database
UDPClient --> MessageRequest
UDPClient --> ClientRouter
ConnectionHandler --> UIEventPublisher
ConnectionHandler --> ClientRouter
ConnectionHandler --> TCPClient
TCPClient --> ConnectionHandler
TCPClient --> ClientRouter
TCPClient --> MessageRequest
TCPClient --> UIEventPublisher
TCPClient --> ChatRepository
MessageHandler <|.. DownloadInitAckHandler
DownloadInitAckHandler --> UIEventPublisher
MessageHandler <|.. SendMessageAckHandler
SendMessageAckHandler --> UIEventPublisher
MessageHandler <|.. UploadStatusHandler
UploadStatusHandler --> UIEventPublisher
MessageHandler <|.. NewMessageHandler
NewMessageHandler --> UIEventPublisher
MessageHandler <|.. ConnectAckHandler
ConnectAckHandler --> UIEventPublisher
MessageHandler <|.. ServerJoinedHandler
ServerJoinedHandler --> UIEventPublisher
MessageHandler <|.. UploadInitAckHandler
UploadInitAckHandler --> UIEventPublisher
MessageHandler <|.. ServerLeftHandler
ServerLeftHandler --> UIEventPublisher
@enduml